# Generated by Django 2.0.7 on 2019-08-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchEngine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='keyword',
            new_name='searchword',
        ),
    ]
